### PR TITLE
Move to QGis 3

### PR DESCRIPTION
**Pull request by Gui0delp**
Hi 🙂,
I would like to propose you this contribution which is a mixture of the good work of @CEZERT and myself. Being a user of your plugin under version 2.X of Qgis I wanted to migrate your plugin for version 3.X of QGis. Indeed, many people wanted this migration in order to be able to take advantage of its features. I really think that the migration of this plugin is a good thing because there is no equivalent on QGis 3.X, at least not to my knowledge.
I hope this contribution will grab your attention.

Have a nice day.

Kind regards

### CODE REVIEW

**Review by CEZERT — APPROVED** [review]

**Comment by simgislab** [comment]
merged, but the future of this plugin in unclear

**Comment by simgislab** [comment]
I wonder why did you delete the LICENSE and Readme though

**Comment by Gui0delp** [comment]
Hi,
Oh it's a mistake from me...
Sorry about that

**Comment by simgislab** [comment]
ok, will put it back

**Comment by eduard-kazakov** [comment]
@Gui0delp @CEZERT 
Plugin is now available for QGIS3 in standard repository: https://plugins.qgis.org/plugins/reconstruct_line/
Thanks for your contribution.

**Pull request merged**
